[package]
name = "babel_monitor"
version = "0.1.0"
authors = ["jkilpatr <jkilpatr@redhat.com>"]

[dependencies]
mockstream = { git = "https://github.com/lazy-bitfield/rust-mockstream.git" }
ascii = "0.8.6"
bufstream = "0.1"
ip_network = "0.1"
failure = "0.1.1"
log = "^0.4"
