[package]
authors = ["Jehan <jehan.tremback@gmail.com>", "Ben <wangben3@gmail.com>"]
build = "build.rs"
name = "rita"
version = "0.1.14"
[[bin]]
name = "rita_exit"
path = "src/exit.rs"

[[bin]]
name = "rita"
path = "src/client.rs"

[dependencies]
actix = "0.7.6"
actix_derive = "0.3.2"
bytes = "0.4.11"
config = "0.9.1"
docopt = "1.0.2"
dotenv = "0.13.0"
env_logger = "0.6.0"
failure = "0.1.3"
futures = "0.1.25"
handlebars = "1.1.0"
ipnetwork = "0.13.1"
lazy_static = "1.2.0"
log = "0.4.6"
minihttpse = "0.1.6"
mockito = "0.13.0"
num-traits = "0.2.6"
num256 = "0.1.1"
openssl-probe = "0.1.2"
rand = "0.6.0"
regex = "1.0.6"
reqwest = "0.9.5"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
syslog = "4.0.1"
tokio = "0.1.11"
tokio-codec = "0.1.1"
tokio-io = "0.1.10"
trust-dns-resolver = "0.10.0"

[dependencies.actix-web]
default_features = false
version = "0.7.14"

[dependencies.althea_kernel_interface]
path = "../althea_kernel_interface"

[dependencies.althea_types]
features = ["actix"]
path = "../althea_types"

[dependencies.babel_monitor]
path = "../babel_monitor"

[dependencies.byteorder]
features = ["i128"]
version = "1.2.7"

[dependencies.clu]
path = "../clu"

[dependencies.diesel]
features = ["sqlite"]
version = "1.3.3"

[dependencies.eui48]
git = "https://github.com/althea-mesh/eui48.git"

[dependencies.exit_db]
path = "../exit_db"

[dependencies.lettre]
git = "https://github.com/lettre/lettre.git"

[dependencies.lettre_email]
git = "https://github.com/lettre/lettre.git"

[dependencies.libsqlite3-sys]
features = ["bundled"]
version = "0.9.1"

[dependencies.mockstream]
git = "https://github.com/lazy-bitfield/rust-mockstream.git"

[dependencies.settings]
path = "../settings"

[features]
default = []
development = []
system_alloc = []
