[package]
authors = ["Jehan <jehan.tremback@gmail.com>"]
name = "althea_types"
version = "0.1.0"
[dependencies]
base64 = "0.10.0"
ethereum-types = "0.4.0"
hex = "0.3.2"
num256 = "0.1.1"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"

[dependencies.actix]
optional = true
version = "0.7.6"

[dependencies.eui48]
features = ["serde"]
git = "https://github.com/althea-mesh/eui48"
