[package]
authors = ["Justin <kilpatrickjustin@protonmail.ch>"]
name = "clu"
version = "0.0.1"
[dependencies]
env_logger = "0.6.0"
failure = "0.1.3"
ipgen = "0.0.4"
lazy_static = "1.2.0"
log = "0.4.6"
rand = "0.6.0"
regex = "1.0.6"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"

[dependencies.althea_kernel_interface]
path = "../althea_kernel_interface"

[dependencies.althea_types]
path = "../althea_types"

[dependencies.babel_monitor]
path = "../babel_monitor"

[dependencies.settings]
path = "../settings"
